run-name: Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SAST:
    uses: /iranherr/devsecops/.github/workflows/ci/templateSast.yml@main
    with:
      run-name: "Análisis de Código"
    secrets: inherit 
