name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Analitics-SAST.yml
      - run: npm run style:check
      - run: npm test
