name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] 
jobs:
  SonarCloudSAST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Análisis SAST
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  DependencyCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'devsecops'
          path: '.'
          format: 'HTML'
          
      - name: Reporte de resultados
        uses: actions/upload-artifact@master
        with:
           name: Dependency report
           path: ${{github.workspace}}/reports
