run-name: Workflow 

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  SAST:
   uses: ./.github/workflows/ci/template-SAST.yml
   secrets: inherit
